# Generated by Django 3.1.1 on 2020-09-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=48, verbose_name='Производитель')),
                ('model', models.CharField(max_length=48, verbose_name='Модель')),
                ('issuance', models.PositiveIntegerField(default=0, verbose_name='Год выпуска')),
                ('transmission', models.SmallIntegerField(choices=[(1, 'Mechanics'), (2, 'Automatic'), (3, 'Robot')], default=2, verbose_name='Коробка')),
                ('color', models.CharField(max_length=25, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ('manufacturer',),
            },
        ),
    ]
